export const dairy_products = [
  {
    id: 100001,
    product_name: "Milk",
    price_inr: 30.0,
    quantity: "1 liter",
    calories: 60,
    image: "https://example.com/milk_image.jpg",
    quality: "4/5",
  },
  {
    id: 100002,
    product_name: "Paneer",
    price_inr: 200.0,
    quantity: "250g",
    calories: 300,
    image: "https://example.com/paneer_image.jpg",
    quality: "3.5/5",
  },
  {
    id: 100003,
    product_name: "Curd",
    price_inr: 40.0,
    quantity: "500g",
    calories: 100,
    image: "https://example.com/curd_image.jpg",
    quality: "4.2/5",
  },
  {
    id: 100004,
    product_name: "Butter",
    price_inr: 120.0,
    quantity: "200g",
    calories: 720,
    image: "https://example.com/butter_image.jpg",
    quality: "4.7/5",
  },
  {
    id: 100005,
    product_name: "Greek Yogurt",
    price_inr: 70.0,
    quantity: "500g",
    calories: 150,
    image: "https://example.com/greek_yogurt_image.jpg",
    quality: "4.5/5",
  },
  {
    id: 100006,
    product_name: "Goat Cheese",
    price_inr: 180.0,
    quantity: "200g",
    calories: 280,
    image: "https://example.com/goat_cheese_image.jpg",
    quality: "4.7/5",
  },
  {
    id: 100007,
    product_name: "Sour Cream",
    price_inr: 45.0,
    quantity: "300g",
    calories: 120,
    image: "https://example.com/sour_cream_image.jpg",
    quality: "4.2/5",
  },
  {
    id: 100008,
    product_name: "Ricotta Cheese",
    price_inr: 150.0,
    quantity: "250g",
    calories: 320,
    image: "https://example.com/ricotta_cheese_image.jpg",
    quality: "4.6/5",
  },
  {
    id: 100009,
    product_name: "Mozzarella Cheese",
    price_inr: 130.0,
    quantity: "200g",
    calories: 240,
    image: "https://example.com/mozzarella_cheese_image.jpg",
    quality: "4.4/5",
  },
  {
    id: 100010,
    product_name: "Yogurt Drink",
    price_inr: 55.0,
    quantity: "500ml",
    calories: 160,
    image: "https://example.com/yogurt_drink_image.jpg",
    quality: "4.0/5",
  },

  {
    id: 100011,
    product_name: "Milkshake",
    price_inr: 50.0,
    quantity: "400ml",
    calories: 180,
    image: "https://example.com/milkshake_image.jpg",
    quality: "4.6/5",
  },
  {
    id: 100012,
    product_name: "Cottage Cheese",
    price_inr: 90.0,
    quantity: "200g",
    calories: 180,
    image: "https://example.com/cottage_cheese_image.jpg",
    quality: "4.0/5",
  },
  {
    id: 100013,
    product_name: "Whipped Cream",
    price_inr: 120.0,
    quantity: "150g",
    calories: 450,
    image: "https://example.com/whipped_cream_image.jpg",
    quality: "4.8/5",
  },
  // ... (previous products)

  {
    id: 100014,
    product_name: "Flavored Yogurt",
    price_inr: 60.0,
    quantity: "400g",
    calories: 200,
    image: "https://example.com/flavored_yogurt_image.jpg",
    quality: "4.3/5",
  },
  {
    id: 100015,
    product_name: "Chocolate Milk",
    price_inr: 35.0,
    quantity: "500ml",
    calories: 120,
    image: "https://example.com/chocolate_milk_image.jpg",
    quality: "4.5/5",
  },
  {
    id: 100016,
    product_name: "Condensed Milk",
    price_inr: 80.0,
    quantity: "400g",
    calories: 350,
    image: "https://example.com/condensed_milk_image.jpg",
    quality: "4.2/5",
  },
  {
    id: 100017,
    product_name: "Almond Milk",
    price_inr: 120.0,
    quantity: "1 liter",
    calories: 80,
    image: "https://example.com/almond_milk_image.jpg",
    quality: "4.6/5",
  },

  {
    id: 100033,
    product_name: "Brazil Nut Milk",
    price_inr: 70.0,
    quantity: "1 liter",
    calories: 80,
    image: "https://example.com/brazil_nut_milk_image.jpg",
    quality: "4.4/5",
  },
  {
    id: 100034,
    product_name: "Blueberry Yogurt",
    price_inr: 60.0,
    quantity: "400g",
    calories: 150,
    image: "https://example.com/blueberry_yogurt_image.jpg",
    quality: "4.5/5",
  },
  {
    id: 100035,
    product_name: "Flaxseed Butter",
    price_inr: 100.0,
    quantity: "250g",
    calories: 550,
    image: "https://example.com/flaxseed_butter_image.jpg",
    quality: "4.3/5",
  },
  {
    id: 100036,
    product_name: "Sesame Seed Milk",
    price_inr: 50.0,
    quantity: "500ml",
    calories: 100,
    image: "https://example.com/sesame_seed_milk_image.jpg",
    quality: "4.6/5",
  },
  // ... (previous products)

  {
    id: 100037,
    product_name: "Peanut Butter",
    price_inr: 100.0,
    quantity: "200g",
    calories: 580,
    image: "https://example.com/peanut_butter_image.jpg",
    quality: "4.7/5",
  },
  {
    id: 100038,
    product_name: "Hazelnut Milk",
    price_inr: 50.0,
    quantity: "1 liter",
    calories: 70,
    image: "https://example.com/hazelnut_milk_image.jpg",
    quality: "4.5/5",
  },
  {
    id: 100039,
    product_name: "Cheddar Cheese",
    price_inr: 160.0,
    quantity: "200g",
    calories: 280,
    image: "https://example.com/cheddar_cheese_image.jpg",
    quality: "4.6/5",
  },
  {
    id: 100040,
    product_name: "Sunflower Seed Butter",
    price_inr: 120.0,
    quantity: "250g",
    calories: 540,
    image: "https://example.com/sunflower_seed_butter_image.jpg",
    quality: "4.3/5",
  },
  {
    id: 100043,
    product_name: "Coconut Cream",
    price_inr: 70.0,
    quantity: "150ml",
    calories: 200,
    image: "https://example.com/coconut_cream_image.jpg",
    quality: "4.0/5",
  },
  {
    id: 100044,
    product_name: "Pecan Butter",
    price_inr: 140.0,
    quantity: "200g",
    calories: 600,
    image: "https://example.com/pecan_butter_image.jpg",
    quality: "4.4/5",
  },
  {
    id: 100045,
    product_name: "Tofu",
    price_inr: 30.0,
    quantity: "300g",
    calories: 180,
    image: "https://example.com/tofu_image.jpg",
    quality: "3.9/5",
  },
  {
    id: 100046,
    product_name: "Walnut Butter",
    price_inr: 130.0,
    quantity: "250g",
    calories: 590,
    image: "https://example.com/walnut_butter_image.jpg",
    quality: "4.5/5",
  },
  {
    id: 100047,
    product_name: "Macadamia Nut Milk",
    price_inr: 80.0,
    quantity: "500ml",
    calories: 120,
    image: "https://example.com/macadamia_nut_milk_image.jpg",
    quality: "4.2/5",
  },
  {
    id: 100048,
    product_name: "Cashew Milk",
    price_inr: 60.0,
    quantity: "500ml",
    calories: 90,
    image: "https://example.com/cashew_milk_image.jpg",
    quality: "4.4/5",
  },
  {
    id: 100049,
    product_name: "Pistachio Butter",
    price_inr: 150.0,
    quantity: "200g",
    calories: 550,
    image: "https://example.com/pistachio_butter_image.jpg",
    quality: "4.6/5",
  },
  {
    id: 100050,
    product_name: "Quark",
    price_inr: 70.0,
    quantity: "300g",
    calories: 120,
    image: "https://example.com/quark_image.jpg",
    quality: "4.2/5",
  },
  {
    id: 100051,
    product_name: "Oat Milk",
    price_inr: 45.0,
    quantity: "1 liter",
    calories: 60,
    image: "https://example.com/oat_milk_image.jpg",
    quality: "4.5/5",
  },
  {
    id: 100052,
    product_name: "Camembert Cheese",
    price_inr: 180.0,
    quantity: "250g",
    calories: 320,
    image: "https://example.com/camembert_cheese_image.jpg",
    quality: "4.7/5",
  },
  {
    id: 100053,
    product_name: "Pomegranate Yogurt",
    price_inr: 55.0,
    quantity: "400g",
    calories: 150,
    image: "https://example.com/pomegranate_yogurt_image.jpg",
    quality: "4.3/5",
  },
  {
    id: 100054,
    product_name: "Avocado Butter",
    price_inr: 100.0,
    quantity: "250g",
    calories: 540,
    image: "https://example.com/avocado_butter_image.jpg",
    quality: "4.6/5",
  },
  {
    id: 100055,
    product_name: "Hazelnut Butter",
    price_inr: 120.0,
    quantity: "200g",
    calories: 580,
    image: "https://example.com/hazelnut_butter_image.jpg",
    quality: "4.7/5",
  },
  {
    id: 100056,
    product_name: "Pumpkin Seed Milk",
    price_inr: 50.0,
    quantity: "500ml",
    calories: 100,
    image: "https://example.com/pumpkin_seed_milk_image.jpg",
    quality: "4.6/5",
  },
  {
    id: 100057,
    product_name: "Blackberry Yogurt",
    price_inr: 60.0,
    quantity: "400g",
    calories: 150,
    image: "https://example.com/blackberry_yogurt_image.jpg",
    quality: "4.5/5",
  },
  {
    id: 100058,
    product_name: "Coconut Butter",
    price_inr: 80.0,
    quantity: "200g",
    calories: 600,
    image: "https://example.com/coconut_butter_image.jpg",
    quality: "4.8/5",
  },
  {
    id: 100059,
    product_name: "Soy Milk",
    price_inr: 40.0,
    quantity: "1 liter",
    calories: 70,
    image: "https://example.com/soy_milk_image.jpg",
    quality: "4.2/5",
  },
  {
    id: 100060,
    product_name: "Cranberry Yogurt",
    price_inr: 65.0,
    quantity: "350g",
    calories: 160,
    image: "https://example.com/cranberry_yogurt_image.jpg",
    quality: "4.4/5",
  },
  {
    id: 100061,
    product_name: "Apricot Milk",
    price_inr: 55.0,
    quantity: "500ml",
    calories: 120,
    image: "https://example.com/apricot_milk_image.jpg",
    quality: "4.5/5",
  },
  {
    id: 100062,
    product_name: "Gouda Cheese",
    price_inr: 170.0,
    quantity: "200g",
    calories: 280,
    image: "https://example.com/gouda_cheese_image.jpg",
    quality: "4.6/5",
  },
];
